/**
 * Row element model (documentation only).
 *
 * A row is currently materialized as a collection of seat placements
 * generated by the row/arc tools.
 *
 * @typedef {Object} RowModel
 * @property {string} id
 * @property {string} label
 * @property {Array<string>} seatIds
 * @property {{x:number,y:number}} [startPoint]
 * @property {{x:number,y:number}} [endPoint]
 * @property {number} [seatCount]
 * @property {number} [rotation]
 */

export const ROW_MODEL_FIELDS = Object.freeze([
    "id",
    "label",
    "seatIds",
    "startPoint",
    "endPoint",
    "seatCount",
    "rotation",
]);
